---
# Source: retail-store-sample-catalog-chart/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: retail-store-catalog
  labels:
    helm.sh/chart: catalog-0.8.4
    app.kubernetes.io/name: catalog
    app.kubernetes.io/instance: retail-store-catalog
    app.kubernetes.io/component: service
    app.kuberneres.io/owner: retail-store-sample
    app.kubernetes.io/managed-by: Helm
---
# Source: retail-store-sample-catalog-chart/templates/mysql-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: catalog-db
data:
  username: "Y2F0YWxvZw=="
  password: "d0ljNkJ5dkJLbzdldW5oQw=="
---
# Source: retail-store-sample-catalog-chart/templates/configmap.yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: retail-store-catalog
data:
  DB_ENDPOINT: retail-store-catalog-mysql:3306
  DB_READ_ENDPOINT: retail-store-catalog-mysql:3306
  DB_NAME: catalog
---
# Source: retail-store-sample-catalog-chart/templates/mysql-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: retail-store-catalog-mysql
  labels:
    helm.sh/chart: catalog-0.8.4
    app.kubernetes.io/name: retail-store-catalog
    app.kubernetes.io/instance: retail-store-catalog
    app.kubernetes.io/component: mysql
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: mysql
      protocol: TCP
      name: mysql
  selector:
    app.kubernetes.io/name: retail-store-catalog
    app.kubernetes.io/instance: retail-store-catalog
    app.kubernetes.io/component: mysql
---
# Source: retail-store-sample-catalog-chart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: retail-store-catalog
  labels:
    helm.sh/chart: catalog-0.8.4
    app.kubernetes.io/name: catalog
    app.kubernetes.io/instance: retail-store-catalog
    app.kubernetes.io/component: service
    app.kuberneres.io/owner: retail-store-sample
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: catalog
    app.kubernetes.io/instance: retail-store-catalog
    app.kubernetes.io/component: service
    app.kuberneres.io/owner: retail-store-sample
---
# Source: retail-store-sample-catalog-chart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: retail-store-catalog
  labels:
    helm.sh/chart: catalog-0.8.4
    app.kubernetes.io/name: catalog
    app.kubernetes.io/instance: retail-store-catalog
    app.kubernetes.io/component: service
    app.kuberneres.io/owner: retail-store-sample
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 0
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: catalog
      app.kubernetes.io/instance: retail-store-catalog
      app.kubernetes.io/component: service
      app.kuberneres.io/owner: retail-store-sample
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      labels:
        app.kubernetes.io/name: catalog
        app.kubernetes.io/instance: retail-store-catalog
        app.kubernetes.io/component: service
        app.kuberneres.io/owner: retail-store-sample
    spec:
      serviceAccountName: retail-store-catalog
      securityContext:
        fsGroup: 1000
      containers:
        - name: catalog
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: catalog-db
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: catalog-db
                  key: password
          envFrom:
            - configMapRef:
                name: retail-store-catalog
          securityContext:
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
          image: "public.ecr.aws/aws-containers/retail-store-sample-catalog:0.8.4"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 3
          resources:
            limits:
              memory: 256Mi
            requests:
              cpu: 128m
              memory: 256Mi
          volumeMounts:
            - mountPath: /tmp
              name: tmp-volume
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
---
# Source: retail-store-sample-catalog-chart/templates/mysql-statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: retail-store-catalog-mysql
  labels:
    helm.sh/chart: catalog-0.8.4
    app.kubernetes.io/name: retail-store-catalog
    app.kubernetes.io/instance: retail-store-catalog
    app.kubernetes.io/component: mysql
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  serviceName: retail-store-catalog-mysql
  selector:
    matchLabels:
      app.kubernetes.io/name: retail-store-catalog
      app.kubernetes.io/instance: retail-store-catalog
      app.kubernetes.io/component: mysql
  template:
    metadata:
      labels:
        app.kubernetes.io/name: retail-store-catalog
        app.kubernetes.io/instance: retail-store-catalog
        app.kubernetes.io/component: mysql
    spec:
      containers:
        - name: mysql
          image: "public.ecr.aws/docker/library/mysql:8.0"
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: my-secret-pw
            - name: MYSQL_DATABASE
              value: catalog
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: catalog-db
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: catalog-db
                  key: password
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
          ports:
            - name: mysql
              containerPort: 3306
              protocol: TCP
      volumes:
      - name: data
        emptyDir: {}
---
# Source: retail-store-sample-catalog-chart/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "retail-store-catalog-test-connection"
  labels:
    helm.sh/chart: catalog-0.8.4
    app.kubernetes.io/name: catalog
    app.kubernetes.io/instance: retail-store-catalog
    app.kubernetes.io/component: service
    app.kuberneres.io/owner: retail-store-sample
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['retail-store-catalog:80/health']
  restartPolicy: Never
