---
# Source: retail-store-sample-checkout-chart/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: retail-store-checkout
  labels:
    helm.sh/chart: checkout-0.8.4
    app.kubernetes.io/name: checkout
    app.kubernetes.io/instance: retail-store-checkout
    app.kubernetes.io/component: service
    app.kuberneres.io/owner: retail-store-sample
    app.kubernetes.io/managed-by: Helm
---
# Source: retail-store-sample-checkout-chart/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: retail-store-checkout
data:
  REDIS_URL: redis://retail-store-checkout-redis:6379
---
# Source: retail-store-sample-checkout-chart/templates/redis-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: retail-store-checkout-redis
  labels:
    helm.sh/chart: checkout-0.8.4
    app.kubernetes.io/name: retail-store-checkout
    app.kubernetes.io/instance: retail-store-checkout
    app.kubernetes.io/component: redis
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    app.kubernetes.io/name: retail-store-checkout
    app.kubernetes.io/instance: retail-store-checkout
    app.kubernetes.io/component: redis
---
# Source: retail-store-sample-checkout-chart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: retail-store-checkout
  labels:
    helm.sh/chart: checkout-0.8.4
    app.kubernetes.io/name: checkout
    app.kubernetes.io/instance: retail-store-checkout
    app.kubernetes.io/component: service
    app.kuberneres.io/owner: retail-store-sample
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: checkout
    app.kubernetes.io/instance: retail-store-checkout
    app.kubernetes.io/component: service
    app.kuberneres.io/owner: retail-store-sample
---
# Source: retail-store-sample-checkout-chart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: retail-store-checkout
  labels:
    helm.sh/chart: checkout-0.8.4
    app.kubernetes.io/name: checkout
    app.kubernetes.io/instance: retail-store-checkout
    app.kubernetes.io/component: service
    app.kuberneres.io/owner: retail-store-sample
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: checkout
      app.kubernetes.io/instance: retail-store-checkout
      app.kubernetes.io/component: service
      app.kuberneres.io/owner: retail-store-sample
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      labels:
        app.kubernetes.io/name: checkout
        app.kubernetes.io/instance: retail-store-checkout
        app.kubernetes.io/component: service
        app.kuberneres.io/owner: retail-store-sample
    spec:
      serviceAccountName: retail-store-checkout
      securityContext:
        fsGroup: 1000
      containers:
        - name: checkout
          envFrom:
            - configMapRef:
                name: retail-store-checkout
          securityContext:
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
          image: "public.ecr.aws/aws-containers/retail-store-sample-checkout:0.8.4"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 3
          resources:
            limits:
              memory: 256Mi
            requests:
              cpu: 128m
              memory: 256Mi
          volumeMounts:
            - mountPath: /tmp
              name: tmp-volume
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
---
# Source: retail-store-sample-checkout-chart/templates/redis-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: retail-store-checkout-redis
  labels:
    helm.sh/chart: checkout-0.8.4
    app.kubernetes.io/name: retail-store-checkout
    app.kubernetes.io/instance: retail-store-checkout
    app.kubernetes.io/component: redis
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: retail-store-checkout
      app.kubernetes.io/instance: retail-store-checkout
      app.kubernetes.io/component: redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: retail-store-checkout
        app.kubernetes.io/instance: retail-store-checkout
        app.kubernetes.io/component: redis
    spec:
      containers:
        - name: redis
          image: "redis:6.0-alpine"
          imagePullPolicy: IfNotPresent
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
---
# Source: retail-store-sample-checkout-chart/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "retail-store-checkout-test-connection"
  labels:
    helm.sh/chart: checkout-0.8.4
    app.kubernetes.io/name: checkout
    app.kubernetes.io/instance: retail-store-checkout
    app.kubernetes.io/component: service
    app.kuberneres.io/owner: retail-store-sample
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['retail-store-checkout:80/health']
  restartPolicy: Never
